# Generated by Django 3.2.6 on 2021-08-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_text', models.TextField(max_length=10000)),
                ('blog_owner', models.CharField(max_length=15)),
            ],
        ),
    ]
