# Generated by Django 3.2.6 on 2021-08-11 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_slug',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_time',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 10, 41, 43, 985423, tzinfo=utc)),
        ),
    ]
