# Generated by Django 3.2.6 on 2021-08-11 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210811_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_time',
            field=models.DateField(default=datetime.datetime(2021, 8, 11, 10, 50, 40, 992969, tzinfo=utc)),
        ),
    ]
