# Generated by Django 3.2.6 on 2021-08-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_blogpost_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_text',
            field=models.TextField(max_length=1024280),
        ),
    ]
